name: ğŸš€ Update casks

on:
  workflow_dispatch: {}

permissions:
  actions: write
  contents: write
jobs:
  update-casks:
    name: Update casks
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: âš™ï¸ Run bash script
        run: bash update.sh

      - name: ğŸ“ Git status
        run: git status

      - name: ğŸ“ Commit changes
        uses: EndBug/add-and-commit@v9
